# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

org.gradle.configuration-cache=false


# Mod properties
mod_version=0.1-SNAPSHOT
maven_group=io.github.randomusert.mods.randomuserts_utils
archives_name=randomuserts-utils
enabled_platforms=fabric

# Minecraft properties
minecraft_version=26.1.2


# Dependencies
fabric_loader_version=0.19.3
fabric_api_version=0.155.2+26.1.2
