architectury {
    platformSetupLoomIde()
    fabric()
}

configurations {
    common
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentFabric.extendsFrom common
}


repositories {
    maven {
        name = "Terraformers"
        url = "https://maven.terraformersmc.com/"
    }

    maven {
        name = "Refined Storage"
        url = uri("https://maven.creeperhost.net")
        content {
            includeGroup("com.refinedmods.refinedstorage")
        }
    }
}

dependencies {
    implementation "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"

    implementation "net.fabricmc.fabric-api:fabric-api:$rootProject.fabric_api_version"

    implementation("com.terraformersmc:modmenu:18.0.0")

    api("com.refinedmods.refinedstorage:refinedstorage-fabric:3.2.1")

    common(project(path: ':core')) { transitive false }
}


processResources {
    inputs.property 'mod_version', rootProject.mod_version

    filesMatching('fabric.mod.json') {
        expand mod_version: rootProject.mod_version
    }
}